// This file is generated by FlutterFire CLI.
// Run: flutterfire configure
// to regenerate this file with your Firebase project credentials.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase project config (run: flutterfire configure)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: 'REPLACE_WITH_YOUR_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnnck_mKydW7YNLqq4oCJTdBMnwRI3KHA',
    appId: '1:125024595843:android:032b46e9d41018be3810b6',
    messagingSenderId: '125024595843',
    projectId: 'tradepact-bcb22',
    storageBucket: 'tradepact-bcb22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnegStyc6a7yLl-jigdB_3mhFF7TEGuEc',
    appId: '1:125024595843:ios:e54449a793c234813810b6',
    messagingSenderId: '125024595843',
    projectId: 'tradepact-bcb22',
    storageBucket: 'tradepact-bcb22.firebasestorage.app',
    androidClientId: '125024595843-oqn43std6pujd68876hsetf2budkoasg.apps.googleusercontent.com',
    iosClientId: '125024595843-omhuqof1tcddkkt01ubpu3mmcorchcfa.apps.googleusercontent.com',
    iosBundleId: 'com.jaysisharma.tradepact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: 'REPLACE_WITH_YOUR_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
    iosClientId: 'REPLACE_WITH_YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.jaysi.tradepact',
  );
}